[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev:fast"
  port = 3000
  targetPort = 5173
  publish = "dist"
  autoLaunch = true
  framework = "#custom"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**/*.cjs"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify functions are handled automatically, no need for explicit redirects

# Stackbit configuration
[stackbit]
  # Use npx to run vite with optimizations
  dev_command = "npx vite --port {PORT} --strictPort=false --force"
